namespace Test.Namespace.Game
{
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Entitas.CodeGeneration.Plugins.ComponentEntityApiGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
public partial class GameEntity {

    public Particle.Sprite2DComponent particleSprite2D { get { return (Particle.Sprite2DComponent)GetComponent(GameComponentsLookup.ParticleSprite2D); } }
    public bool hasParticleSprite2D { get { return HasComponent(GameComponentsLookup.ParticleSprite2D); } }

    public void AddParticleSprite2D(int newSpriteId, byte[] newVertices, int newTextureLayer, float newWidth, float newHeight) {
        var index = GameComponentsLookup.ParticleSprite2D;
        var component = (Particle.Sprite2DComponent)CreateComponent(index, typeof(Particle.Sprite2DComponent));
        component.SpriteId = newSpriteId;
        component.Vertices = newVertices;
        component.TextureLayer = newTextureLayer;
        component.Width = newWidth;
        component.Height = newHeight;
        AddComponent(index, component);
    }

    public void ReplaceParticleSprite2D(int newSpriteId, byte[] newVertices, int newTextureLayer, float newWidth, float newHeight) {
        var index = GameComponentsLookup.ParticleSprite2D;
        var component = (Particle.Sprite2DComponent)CreateComponent(index, typeof(Particle.Sprite2DComponent));
        component.SpriteId = newSpriteId;
        component.Vertices = newVertices;
        component.TextureLayer = newTextureLayer;
        component.Width = newWidth;
        component.Height = newHeight;
        ReplaceComponent(index, component);
    }

    public void RemoveParticleSprite2D() {
        RemoveComponent(GameComponentsLookup.ParticleSprite2D);
    }
}

}
namespace Test.Namespace.Game
{
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Entitas.CodeGeneration.Plugins.ComponentMatcherApiGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
public sealed partial class GameMatcher {

    static Entitas.IMatcher<GameEntity> _matcherParticleSprite2D;

    public static Entitas.IMatcher<GameEntity> ParticleSprite2D {
        get {
            if (_matcherParticleSprite2D == null) {
                var matcher = (Entitas.Matcher<GameEntity>)Entitas.Matcher<GameEntity>.AllOf(GameComponentsLookup.ParticleSprite2D);
                matcher.componentNames = GameComponentsLookup.componentNames;
                _matcherParticleSprite2D = matcher;
            }

            return _matcherParticleSprite2D;
        }
    }
}

}