namespace Test.Namespace.Game
{
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Entitas.CodeGeneration.Plugins.ComponentEntityApiGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
public partial class GameEntity {

    public Particle.Box2DColliderComponent particleBox2DCollider { get { return (Particle.Box2DColliderComponent)GetComponent(GameComponentsLookup.ParticleBox2DCollider); } }
    public bool hasParticleBox2DCollider { get { return HasComponent(GameComponentsLookup.ParticleBox2DCollider); } }

    public void AddParticleBox2DCollider(int newTest, float newOffSetX, float newOffsetY, float newWidth, float newHeight) {
        var index = GameComponentsLookup.ParticleBox2DCollider;
        var component = (Particle.Box2DColliderComponent)CreateComponent(index, typeof(Particle.Box2DColliderComponent));
        component.Test = newTest;
        component.OffSetX = newOffSetX;
        component.OffsetY = newOffsetY;
        component.Width = newWidth;
        component.Height = newHeight;
        AddComponent(index, component);
    }

    public void ReplaceParticleBox2DCollider(int newTest, float newOffSetX, float newOffsetY, float newWidth, float newHeight) {
        var index = GameComponentsLookup.ParticleBox2DCollider;
        var component = (Particle.Box2DColliderComponent)CreateComponent(index, typeof(Particle.Box2DColliderComponent));
        component.Test = newTest;
        component.OffSetX = newOffSetX;
        component.OffsetY = newOffsetY;
        component.Width = newWidth;
        component.Height = newHeight;
        ReplaceComponent(index, component);
    }

    public void RemoveParticleBox2DCollider() {
        RemoveComponent(GameComponentsLookup.ParticleBox2DCollider);
    }
}

}
namespace Test.Namespace.Game
{
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Entitas.CodeGeneration.Plugins.ComponentMatcherApiGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
public sealed partial class GameMatcher {

    static Entitas.IMatcher<GameEntity> _matcherParticleBox2DCollider;

    public static Entitas.IMatcher<GameEntity> ParticleBox2DCollider {
        get {
            if (_matcherParticleBox2DCollider == null) {
                var matcher = (Entitas.Matcher<GameEntity>)Entitas.Matcher<GameEntity>.AllOf(GameComponentsLookup.ParticleBox2DCollider);
                matcher.componentNames = GameComponentsLookup.componentNames;
                _matcherParticleBox2DCollider = matcher;
            }

            return _matcherParticleBox2DCollider;
        }
    }
}

}