namespace Test.Namespace.Game
{
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Entitas.CodeGeneration.Plugins.ComponentEntityApiGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
public partial class GameEntity {

    public Vehicle.BaseComponent vehicleBase { get { return (Vehicle.BaseComponent)GetComponent(GameComponentsLookup.VehicleBase); } }
    public bool hasVehicleBase { get { return HasComponent(GameComponentsLookup.VehicleBase); } }

    public void AddVehicleBase(Int64 newId, float newDurability, bool newEngineRunning, bool newStartingProcedure, bool newEndingProcedure, bool newCanPilot, bool newIsDestroyed) {
        var index = GameComponentsLookup.VehicleBase;
        var component = (Vehicle.BaseComponent)CreateComponent(index, typeof(Vehicle.BaseComponent));
        component.Id = newId;
        component.Durability = newDurability;
        component.EngineRunning = newEngineRunning;
        component.StartingProcedure = newStartingProcedure;
        component.EndingProcedure = newEndingProcedure;
        component.CanPilot = newCanPilot;
        component.IsDestroyed = newIsDestroyed;
        AddComponent(index, component);
    }

    public void ReplaceVehicleBase(Int64 newId, float newDurability, bool newEngineRunning, bool newStartingProcedure, bool newEndingProcedure, bool newCanPilot, bool newIsDestroyed) {
        var index = GameComponentsLookup.VehicleBase;
        var component = (Vehicle.BaseComponent)CreateComponent(index, typeof(Vehicle.BaseComponent));
        component.Id = newId;
        component.Durability = newDurability;
        component.EngineRunning = newEngineRunning;
        component.StartingProcedure = newStartingProcedure;
        component.EndingProcedure = newEndingProcedure;
        component.CanPilot = newCanPilot;
        component.IsDestroyed = newIsDestroyed;
        ReplaceComponent(index, component);
    }

    public void RemoveVehicleBase() {
        RemoveComponent(GameComponentsLookup.VehicleBase);
    }
}

}
namespace Test.Namespace.Game
{
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Entitas.CodeGeneration.Plugins.ComponentMatcherApiGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
public sealed partial class GameMatcher {

    static Entitas.IMatcher<GameEntity> _matcherVehicleBase;

    public static Entitas.IMatcher<GameEntity> VehicleBase {
        get {
            if (_matcherVehicleBase == null) {
                var matcher = (Entitas.Matcher<GameEntity>)Entitas.Matcher<GameEntity>.AllOf(GameComponentsLookup.VehicleBase);
                matcher.componentNames = GameComponentsLookup.componentNames;
                _matcherVehicleBase = matcher;
            }

            return _matcherVehicleBase;
        }
    }
}

}