namespace Test.Namespace.Game
{
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Entitas.CodeGeneration.Plugins.ComponentEntityApiGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
public partial class GameEntity {

    public Particle.AnimationComponent particleAnimation { get { return (Particle.AnimationComponent)GetComponent(GameComponentsLookup.ParticleAnimation); } }
    public bool hasParticleAnimation { get { return HasComponent(GameComponentsLookup.ParticleAnimation); } }

    public void AddParticleAnimation(float newAnimationSpeed, float newCurrentTime, int newCurrentFrame, bool newIsFinished, int newCurrentSpriteId) {
        var index = GameComponentsLookup.ParticleAnimation;
        var component = (Particle.AnimationComponent)CreateComponent(index, typeof(Particle.AnimationComponent));
        component.AnimationSpeed = newAnimationSpeed;
        component.CurrentTime = newCurrentTime;
        component.CurrentFrame = newCurrentFrame;
        component.IsFinished = newIsFinished;
        component.CurrentSpriteId = newCurrentSpriteId;
        AddComponent(index, component);
    }

    public void ReplaceParticleAnimation(float newAnimationSpeed, float newCurrentTime, int newCurrentFrame, bool newIsFinished, int newCurrentSpriteId) {
        var index = GameComponentsLookup.ParticleAnimation;
        var component = (Particle.AnimationComponent)CreateComponent(index, typeof(Particle.AnimationComponent));
        component.AnimationSpeed = newAnimationSpeed;
        component.CurrentTime = newCurrentTime;
        component.CurrentFrame = newCurrentFrame;
        component.IsFinished = newIsFinished;
        component.CurrentSpriteId = newCurrentSpriteId;
        ReplaceComponent(index, component);
    }

    public void RemoveParticleAnimation() {
        RemoveComponent(GameComponentsLookup.ParticleAnimation);
    }
}

}
namespace Test.Namespace.Game
{
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Entitas.CodeGeneration.Plugins.ComponentMatcherApiGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
public sealed partial class GameMatcher {

    static Entitas.IMatcher<GameEntity> _matcherParticleAnimation;

    public static Entitas.IMatcher<GameEntity> ParticleAnimation {
        get {
            if (_matcherParticleAnimation == null) {
                var matcher = (Entitas.Matcher<GameEntity>)Entitas.Matcher<GameEntity>.AllOf(GameComponentsLookup.ParticleAnimation);
                matcher.componentNames = GameComponentsLookup.componentNames;
                _matcherParticleAnimation = matcher;
            }

            return _matcherParticleAnimation;
        }
    }
}

}