namespace Test.Namespace.Game
{
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Entitas.CodeGeneration.Plugins.ComponentEntityApiGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
public partial class GameEntity {

    public Particle.BaseComponent particleBase { get { return (Particle.BaseComponent)GetComponent(GameComponentsLookup.ParticleBase); } }
    public bool hasParticleBase { get { return HasComponent(GameComponentsLookup.ParticleBase); } }

    public void AddParticleBase(int newIndex) {
        var index = GameComponentsLookup.ParticleBase;
        var component = (Particle.BaseComponent)CreateComponent(index, typeof(Particle.BaseComponent));
        component.Index = newIndex;
        AddComponent(index, component);
    }

    public void ReplaceParticleBase(int newIndex) {
        var index = GameComponentsLookup.ParticleBase;
        var component = (Particle.BaseComponent)CreateComponent(index, typeof(Particle.BaseComponent));
        component.Index = newIndex;
        ReplaceComponent(index, component);
    }

    public void RemoveParticleBase() {
        RemoveComponent(GameComponentsLookup.ParticleBase);
    }
}

}
namespace Test.Namespace.Game
{
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Entitas.CodeGeneration.Plugins.ComponentMatcherApiGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
public sealed partial class GameMatcher {

    static Entitas.IMatcher<GameEntity> _matcherParticleBase;

    public static Entitas.IMatcher<GameEntity> ParticleBase {
        get {
            if (_matcherParticleBase == null) {
                var matcher = (Entitas.Matcher<GameEntity>)Entitas.Matcher<GameEntity>.AllOf(GameComponentsLookup.ParticleBase);
                matcher.componentNames = GameComponentsLookup.componentNames;
                _matcherParticleBase = matcher;
            }

            return _matcherParticleBase;
        }
    }
}

}