namespace Test.Namespace.Vehicle
{
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Entitas.CodeGeneration.Plugins.ComponentLookupGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
public static class VehicleComponentsLookup {

    public const int VehicleBase = 0;
    public const int VehicleSprite2D = 1;

    public const int TotalComponents = 2;

    public static readonly string[] componentNames = {
        "VehicleBase",
        "VehicleSprite2D"
    };

    public static readonly System.Type[] componentTypes = {
        typeof(Vehicle.BaseComponent),
        typeof(Vehicle.Sprite2DComponent)
    };
}

}