namespace Test.Namespace.Vehicle
{
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Entitas.CodeGeneration.Plugins.ContextMatcherGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
public sealed partial class VehicleMatcher {

    public static Entitas.IAllOfMatcher<VehicleEntity> AllOf(params int[] indices) {
        return Entitas.Matcher<VehicleEntity>.AllOf(indices);
    }

    public static Entitas.IAllOfMatcher<VehicleEntity> AllOf(params Entitas.IMatcher<VehicleEntity>[] matchers) {
          return Entitas.Matcher<VehicleEntity>.AllOf(matchers);
    }

    public static Entitas.IAnyOfMatcher<VehicleEntity> AnyOf(params int[] indices) {
          return Entitas.Matcher<VehicleEntity>.AnyOf(indices);
    }

    public static Entitas.IAnyOfMatcher<VehicleEntity> AnyOf(params Entitas.IMatcher<VehicleEntity>[] matchers) {
          return Entitas.Matcher<VehicleEntity>.AnyOf(matchers);
    }
}

}