namespace Test.Namespace.Game
{
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Entitas.CodeGeneration.Plugins.ComponentLookupGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
public static class GameComponentsLookup {

    public const int Health = 0;
    public const int ParticleAnimation = 1;
    public const int ParticleBase = 2;
    public const int ParticleBox2DCollider = 3;
    public const int ParticleSprite2D = 4;
    public const int VehicleBase = 5;
    public const int VehicleSprite2D = 6;

    public const int TotalComponents = 7;

    public static readonly string[] componentNames = {
        "Health",
        "ParticleAnimation",
        "ParticleBase",
        "ParticleBox2DCollider",
        "ParticleSprite2D",
        "VehicleBase",
        "VehicleSprite2D"
    };

    public static readonly System.Type[] componentTypes = {
        typeof(HealthComponent),
        typeof(Particle.AnimationComponent),
        typeof(Particle.BaseComponent),
        typeof(Particle.Box2DColliderComponent),
        typeof(Particle.Sprite2DComponent),
        typeof(Vehicle.BaseComponent),
        typeof(Vehicle.Sprite2DComponent)
    };
}

}